# Generated by Django 4.2.7 on 2023-12-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('following', models.IntegerField(blank=True, null=True)),
                ('posts', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('create', 'Create'), ('sync', 'Sync'), ('allocate', 'Allocate')], max_length=100, null=True)),
                ('data_points', models.ManyToManyField(to='SocialBotJobs.datapoint')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interact', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=3)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('os_options', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows')], max_length=10, null=True)),
                ('delay_between_each_task', models.CharField(blank=True, max_length=255, null=True)),
                ('interactions', models.CharField(blank=True, max_length=255, null=True)),
                ('unfollow_after', models.CharField(blank=True, max_length=255, null=True)),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('repeat', models.IntegerField(blank=True, null=True)),
                ('slugs', models.SlugField(max_length=255, null=True)),
                ('bots', models.ManyToManyField(blank=True, to='SocialBotJobs.bot')),
                ('datapoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialBotJobs.datapoint')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialBotJobs.endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('proxy_type', models.CharField(blank=True, choices=[('http', 'HTTP'), ('https', 'HTTPS')], max_length=10, null=True)),
                ('current_usage_count', models.CharField(blank=True, max_length=100, null=True)),
                ('blacklisted', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Resource Manager', 'Resource Manager')], max_length=100)),
                ('end_points', models.ManyToManyField(to='SocialBotJobs.endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('datapoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialBotJobs.datapoint')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialBotJobs.endpoint')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialBotJobs.job')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialBotJobs.service')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialBotJobs.service'),
        ),
    ]
