# Generated by Django 4.2.7 on 2023-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBotJobs', '0002_alter_datapoint_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=50)),
                ('connected', models.CharField(choices=[('worker_1', 'Worker 1'), ('worker_2', 'Worker 2')], default='worker_1', max_length=50)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
