# Generated by Django 4.2.7 on 2023-12-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBotJobs', '0003_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
