# Generated by Django 4.2.7 on 2024-02-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBotJobs', '0007_batch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workflow',
        ),
    ]
