# Generated by Django 4.2.7 on 2024-02-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBotJobs', '0008_delete_workflow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
