# Generated by Django 4.2.7 on 2024-02-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBotJobs', '0009_delete_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='data_points',
        ),
        migrations.RemoveField(
            model_name='service',
            name='end_points',
        ),
        migrations.DeleteModel(
            name='Datapoint',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
