# Generated by Django 4.2.7 on 2024-02-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBotJobs', '0010_delete_bot_remove_endpoint_data_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('email_provider', models.CharField(max_length=255)),
            ],
        ),
    ]
