# Generated by Django 4.2.7 on 2024-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBotJobs', '0011_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralRequest',
            fields=[
                ('request_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('request_type', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('awaiting', 'Awaiting'), ('retry', 'Retry'), ('failed', 'Failed')], default='awaiting', max_length=10)),
                ('payload', models.JSONField()),
            ],
        ),
    ]
