# Generated by Django 4.2.7 on 2024-02-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBotJobs', '0012_centralrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
