# Generated by Django 4.2.7 on 2024-02-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBotJobs', '0013_delete_batch_delete_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proxy',
        ),
    ]
