# Generated by Django 4.2.7 on 2024-02-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBotJobs', '0014_delete_proxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
